remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: <center><span style="font-size: 40px;color:#fcb900;text-decoration: none;">**14th Workshop on Ontology Design and Patterns (WOP 2023)**</span></center>
description: Colocated with the 22nd International Semantic Web Conference (ISWC)
show_downloads: false
extra_css: "/assets/css/custom.css"