remote theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: 14th Workshop on Ontology Design and Patterns (WOP 2023)
description: The disambiguation page for the Workshops on Ontology Design and Patterns
show_downloads: false
