remote theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: 14th Workshop on Ontology Design and Patterns (WOP 2023)
description: Colocated with the 22nd International Semantic Web Conference (ISWC)
show_downloads: false