remote theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: <center><span style="color:brown;"14th Workshop on Ontology Design and Patterns (WOP 2023)</span></center>
description: Colocated with the 22nd International Semantic Web Conference (ISWC)
show_downloads: false