remote theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: <center><span style="font-size: 30px;color:Brown;">**14th Workshop on Ontology Design and Patterns (WOP 2023)**</span> <br><span style="color:black;">Colocated with the <a href="https://iswc2023.semanticweb.org/">22nd International Semantic Web Conference (ISWC 2023)</a></span><br><span style="color:black;"> November 6-10, 2023. Athens, Greece.</span> </center>
description: Colocated with the 22nd International Semantic Web Conference (ISWC)
show_downloads: false

sass:
  style: compressed
  sass_dir: _sass
  scss_dir: _sass
  include:
    - _sass
    - custom.css